import { StyleSheet } from 'react-native';

import { MovieFinderTheme } from '@/constants/movie-finder-theme';

export default StyleSheet.create({
  screen: { backgroundColor: MovieFinderTheme.background, flex: 1 },
  content: { paddingBottom: 36, paddingHorizontal: 24, paddingTop: 20 },
  title: { color: MovieFinderTheme.text, fontSize: 40, fontWeight: '700', letterSpacing: -1.5 },
  subtitle: { color: MovieFinderTheme.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 6 },
  sectionLabel: {
    color: MovieFinderTheme.textSecondary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.05,
    marginBottom: 9,
    marginTop: 29,
  },
  settingRow: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.surface,
    borderBottomColor: MovieFinderTheme.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    paddingHorizontal: 14,
  },
  settingIcon: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blueMuted,
    borderRadius: 11,
    height: 39,
    justifyContent: 'center',
    width: 39,
  },
  settingCopy: { flex: 1, gap: 3 },
  settingTitle: { color: MovieFinderTheme.text, fontSize: 15, fontWeight: '700' },
  settingValue: { color: MovieFinderTheme.textSecondary, fontSize: 13 },
  platforms: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  platform: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.surface,
    borderColor: MovieFinderTheme.line,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  platformSelected: { backgroundColor: MovieFinderTheme.blue, borderColor: MovieFinderTheme.blue },
  platformText: { color: MovieFinderTheme.text, fontSize: 14, fontWeight: '700' },
  platformTextSelected: { color: '#FFFFFF' },
  helperText: { color: MovieFinderTheme.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 12 },
  toggleOn: {
    alignItems: 'flex-end',
    backgroundColor: MovieFinderTheme.blue,
    borderRadius: 20,
    height: 26,
    justifyContent: 'center',
    paddingRight: 3,
    width: 46,
  },
  toggleKnob: { backgroundColor: '#FFFFFF', borderRadius: 10, height: 20, width: 20 },
  saveButton: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blue,
    borderRadius: 13,
    justifyContent: 'center',
    marginTop: 28,
    minHeight: 52,
  },
  saveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  savedNotice: { color: MovieFinderTheme.success, fontSize: 13, fontWeight: '700', marginTop: 10, textAlign: 'center' },
  pressed: { opacity: 0.68 },
});
