import { StyleSheet } from 'react-native';

import { MovieFinderTheme } from '@/constants/movie-finder-theme';

export default StyleSheet.create({
  screen: { backgroundColor: MovieFinderTheme.background, flex: 1, paddingHorizontal: 24, paddingTop: 20 },
  header: { marginBottom: 20 },
  title: { color: MovieFinderTheme.text, fontSize: 40, fontWeight: '700', letterSpacing: -1.4 },
  subtitle: { color: MovieFinderTheme.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 5 },
  searchBox: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.surface,
    borderColor: MovieFinderTheme.line,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    height: 52,
  },
  input: { color: MovieFinderTheme.text, flex: 1, fontSize: 15, height: '100%' },
  resultLabel: {
    color: MovieFinderTheme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.3,
    marginBottom: 10,
    marginTop: 20,
    textTransform: 'uppercase',
  },
  results: { paddingBottom: 104 },
  result: {
    alignItems: 'center',
    borderBottomColor: MovieFinderTheme.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 13,
    paddingVertical: 12,
  },
  poster: { backgroundColor: '#D6D9DE', borderRadius: 8, height: 90, width: 63 },
  resultText: { flex: 1, gap: 4 },
  movieTitle: { color: MovieFinderTheme.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.25 },
  movieMeta: { color: MovieFinderTheme.textSecondary, fontSize: 13 },
  genre: { color: MovieFinderTheme.textSecondary, fontSize: 13 },
  emptyText: { color: MovieFinderTheme.textSecondary, fontSize: 15, marginTop: 35, textAlign: 'center' },
  pressed: { opacity: 0.65 },
  modalBackdrop: { backgroundColor: 'rgba(8, 9, 11, 0.35)', flex: 1, justifyContent: 'flex-end' },
  detailSheet: {
    backgroundColor: MovieFinderTheme.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    minHeight: '70%',
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  handle: { alignSelf: 'center', backgroundColor: '#CCD1D9', borderRadius: 2, height: 4, width: 42 },
  closeButton: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.background,
    borderRadius: 20,
    height: 38,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    top: 18,
    width: 38,
  },
  detailPoster: { alignSelf: 'center', borderRadius: 12, height: 185, marginTop: 20, width: 128 },
  detailTitle: { color: MovieFinderTheme.text, fontSize: 26, fontWeight: '700', letterSpacing: -0.8, marginTop: 16 },
  detailMeta: { color: MovieFinderTheme.textSecondary, fontSize: 14, marginTop: 5 },
  overview: { color: MovieFinderTheme.text, fontSize: 15, lineHeight: 22, marginTop: 16 },
  availability: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blueMuted,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    padding: 11,
  },
  availabilityText: { color: MovieFinderTheme.text, flex: 1, fontSize: 13, lineHeight: 18 },
  detailActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  secondaryAction: {
    alignItems: 'center',
    borderColor: MovieFinderTheme.blue,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  secondaryText: { color: MovieFinderTheme.blue, fontSize: 13, fontWeight: '700' },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blue,
    borderRadius: 12,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  primaryText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  notice: { color: MovieFinderTheme.success, fontSize: 13, fontWeight: '700', marginTop: 11, textAlign: 'center' },
});
