import { StyleSheet } from 'react-native';

import { MovieFinderTheme } from '@/constants/movie-finder-theme';

export default StyleSheet.create({
  screen: { backgroundColor: MovieFinderTheme.background, flex: 1, paddingHorizontal: 24, paddingTop: 20 },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  eyebrow: { color: MovieFinderTheme.textSecondary, fontSize: 11, fontWeight: '700', letterSpacing: 1.25 },
  title: { color: MovieFinderTheme.text, fontSize: 40, fontWeight: '700', letterSpacing: -1.4, marginTop: 3 },
  privateBadge: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blueMuted,
    borderRadius: 20,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  privateText: { color: MovieFinderTheme.blue, fontSize: 12, fontWeight: '700' },
  intro: { color: MovieFinderTheme.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 13 },
  deck: { flex: 1, justifyContent: 'center', maxHeight: 480, minHeight: 360, position: 'relative' },
  backCard: {
    backgroundColor: '#DCE4F0',
    borderRadius: 24,
    bottom: 8,
    left: 9,
    position: 'absolute',
    right: -2,
    top: 8,
    transform: [{ rotate: '2deg' }],
  },
  card: {
    borderRadius: 24,
    elevation: 7,
    flex: 1,
    overflow: 'hidden',
    shadowColor: MovieFinderTheme.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  poster: { height: '100%', width: '100%' },
  posterShade: { backgroundColor: 'rgba(0, 0, 0, 0.48)', bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  cardContent: { bottom: 0, left: 22, position: 'absolute', right: 22 },
  cardMeta: { color: '#E8EEF7', fontSize: 14, fontWeight: '600' },
  movieTitle: { color: '#FFFFFF', fontSize: 36, fontWeight: '700', letterSpacing: -1.2, lineHeight: 40, marginTop: 5 },
  movieDescription: { color: '#E8EEF7', fontSize: 15, lineHeight: 21, marginTop: 7 },
  reasonPill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 16,
    marginBottom: 23,
    marginTop: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reasonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  swipeHint: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'center', marginTop: 22 },
  hintText: { color: MovieFinderTheme.textSecondary, fontSize: 13, fontWeight: '600' },
  hintLine: { backgroundColor: MovieFinderTheme.line, height: 1, marginHorizontal: 5, width: 44 },
  actions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 20,
    justifyContent: 'center',
    paddingBottom: 18,
    paddingTop: 18,
  },
  roundButton: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.surface,
    borderRadius: 30,
    elevation: 2,
    height: 56,
    justifyContent: 'center',
    shadowColor: MovieFinderTheme.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    width: 56,
  },
  primaryRoundButton: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blue,
    borderRadius: 34,
    elevation: 3,
    height: 64,
    justifyContent: 'center',
    shadowColor: MovieFinderTheme.blue,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    width: 64,
  },
  pressed: { opacity: 0.7, transform: [{ scale: 0.96 }] },
});
