import { StyleSheet } from 'react-native';

import { MovieFinderTheme } from '@/constants/movie-finder-theme';

export default StyleSheet.create({
  screen: { backgroundColor: MovieFinderTheme.background, flex: 1 },
  content: { paddingBottom: 28, paddingHorizontal: 24, paddingTop: 20 },
  header: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 28 },
  title: { color: MovieFinderTheme.text, fontSize: 40, fontWeight: '700', letterSpacing: -1.5 },
  count: { color: MovieFinderTheme.textSecondary, fontSize: 16, marginTop: 4 },
  filter: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.surface,
    borderColor: MovieFinderTheme.line,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    marginTop: 3,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  filterText: { color: MovieFinderTheme.blue, fontSize: 16, fontWeight: '600' },
  heroCard: {
    backgroundColor: MovieFinderTheme.surface,
    borderRadius: 22,
    elevation: 3,
    flexDirection: 'row',
    gap: 18,
    overflow: 'hidden',
    padding: 20,
    shadowColor: MovieFinderTheme.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
  },
  heroPoster: { backgroundColor: '#E6E8EB', borderRadius: 13, height: 314, width: 122 },
  heroInfo: { flex: 1 },
  heroTitle: { color: MovieFinderTheme.text, fontSize: 26, fontWeight: '700', letterSpacing: -0.9, lineHeight: 30 },
  reason: { color: MovieFinderTheme.textSecondary, fontSize: 15, lineHeight: 22, marginBottom: 20, marginTop: 18 },
  infoRow: {
    alignItems: 'center',
    borderTopColor: MovieFinderTheme.line,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    minHeight: 56,
    paddingVertical: 8,
  },
  infoText: { color: MovieFinderTheme.text, flex: 1, fontSize: 13, lineHeight: 18 },
  pickButton: {
    alignItems: 'center',
    backgroundColor: MovieFinderTheme.blue,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 15,
    minHeight: 52,
    paddingHorizontal: 9,
  },
  pickText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  choiceBanner: {
    alignItems: 'center',
    backgroundColor: '#E9F8F2',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    padding: 12,
  },
  choiceText: { color: MovieFinderTheme.success, fontSize: 14, fontWeight: '700' },
  queue: { backgroundColor: MovieFinderTheme.surface, borderRadius: 18, marginTop: 18, overflow: 'hidden' },
  queueRow: {
    alignItems: 'center',
    borderBottomColor: MovieFinderTheme.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 13,
    minHeight: 106,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  queuePoster: { backgroundColor: '#E6E8EB', borderRadius: 8, height: 78, width: 56 },
  queueText: { flex: 1, gap: 5 },
  queueTitle: { color: MovieFinderTheme.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.35 },
  queueAvailability: { color: MovieFinderTheme.textSecondary, fontSize: 13, lineHeight: 18 },
  profileLink: { alignItems: 'center', flexDirection: 'row', gap: 7, marginTop: 23, paddingVertical: 10 },
  profileText: { color: MovieFinderTheme.textSecondary, flex: 1, fontSize: 14 },
  profileAction: { color: MovieFinderTheme.blue, fontSize: 14, fontWeight: '600' },
  pressed: { opacity: 0.68 },
});
